[package]
name = "sayhello"
version = "0.1.0"
authors = ["Aditya Kresna <aditya.kresna@outlook.co.id>"]
edition = "2018"

[dependencies]
structopt = { version = "0.3.21", features = ["suggestions", "color", "wrap_help"] }
