[package]
name = "sayhello"
version = "0.1.1"
authors = ["Aditya Kresna <aditya.kresna@outlook.co.id>"]
edition = "2018"

[dependencies]
mimalloc = { version = "0.1.25", default-features = false }
structopt = { version = "0.3.21", features = ["suggestions", "color", "wrap_help"] }
